export const items = [
  {
    id: 1,
    title: "لحم",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "chicken.jpg",
    category: "الفطور",
  },
  {
    id: 2,
    title: "برقر",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "burger.jpg",
    category: "العشاء",
  },
  {
    id: 3,
    title: "بيززا",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "pizza.jpg",
    category: "العشاء",
  },
  {
    id: 4,
    title: "رووووز",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "rice.jpg",
    category: "فطور الصباح",
  },
  {
    id: 5,
    title: "لحم",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "chicken.jpg",
    category: "الفطور",
  },
  {
    id: 6,
    title: "لحم",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "chicken.jpg",
    category: "الفطور",
  },
  {
    id: 7,
    title: "لحم",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "chicken.jpg",
    category: "الإفطار",
  },
  {
    id: 8,
    title: "لحم",
    description: "لحم طعمته سمحة",
    price: "50 دولار",
    image: "chicken.jpg",
    category: "الصحور",
  },
];
